blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponseRedirect
from main import urls as blog_urls
from main.views import index_root
from blog import settings
from django.conf.urls.static import static
from users import urls as users_urls


urlpatterns = [
    path('', index_root),
    path('admin/', admin.site.urls),
    # path('blog/posts/1/', index_root),
    # path('blog/posts', index_root),
    path('blog/', include(blog_urls)),  
    # path('about/', about, name='about'), 
    # path('contacts/', contacts, name='contacts'), 
    # path('post_add/', post_add, name='post_add'), 
    path('users/', include(users_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from .views import (index, post_list, about, contacts, 
                    post_add, post_detail, post_update, post_delete, search)

app_name = 'main'
urlpatterns = [
    
    path('', index), 
    path('about/', about, name='about'), 
    path('contacts/', contacts, name='contacts'), 

    path('posts/', post_list, name='post_list'),
    path('post_add/', post_add, name='post_add'),
    path('posts/<int:pk>/', post_detail, name='post_detail'),
    path('posts/<int:pk>/update/', post_update, name='post_update'),
    path('posts/<int:pk>/delete/', post_delete, name='post_delete'),
    path('posts/search/', search, name='search'),
]

users/urls.py
from django.urls import path
from .views import register, log_in, log_out, get_user_info

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path("user/<int:pk>/", get_user_info, name='user_info'),
]

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name='Автор', editable=False)
    title = models.CharField(max_length=200, verbose_name='Title', blank=False)
    text = models.TextField(blank=False, verbose_name='Text')
    created_date = models.DateTimeField(default=timezone.now, editable=False)
    publish_date = models.DateTimeField(blank=True, null=True, editable=False)
    image = models.ImageField(upload_to='posts/', blank=True, null=True, verbose_name="Изображение поста")

    class Meta:
        verbose_name='Post'
        verbose_name_plural='Posts'
        ordering = ['created_date',]
    
    
    def publish(self):
        self.publish_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post


# class PostForm(forms.Form):
#     # author = forms.CharField(max_length=50, label='Автор')
#     title = forms.CharField(max_length=200, label='Title')
#     text = forms.CharField()
#     image = forms.ImageField(required=False)


class PostForm(forms.ModelForm):
    # author = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.ModelChoiceField(attrs={"readonly":"readonly"}))
    class Meta:
        model = Post
        fields = "__all__"
        # exclude = ['author']
        

main/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import HttpResponsePermanentRedirect
from django.contrib.auth.decorators import login_required
from .models import Post
from .forms import PostForm

# Create your views here.

menu = [{'title': 'Posts', 'url_name': 'main:post_list'}, 
        {'title': 'Add posts', 'url_name': 'main:post_add'},
        {'title': 'About site', 'url_name': 'main:about'},
        {'title': 'Contacts', 'url_name': 'main:contacts'},
        ]

# главная страница сайта
def index_root(request):
    return redirect(post_list)

# главная cтраница приложения main
def index(request):
    return HttpResponsePermanentRedirect("/blog/posts")


def about(request):
    context={'menu': menu}
    return render(request, 'main/about.html', context=context)

def contacts(request):
    context={'menu': menu}
    return render(request, 'main/contacts.html', context=context)



# отображение списка постов
def post_list(request, results=None):
    if results is None:       
    # получаем все объекты таблицы(модели) Post
        posts = Post.objects.all()
    else:
        posts = results
    # заносим их  в объeкт-контекста для передачи в шаблон
    context = {'posts': posts, 'menu': menu}
    return render(request, template_name='main/post_list.html', context=context)

@login_required
def post_add(request):
    title = "Создать пост"
    if request.method == "GET":
        form = PostForm()
        context = {'title': title, "menu": menu, "form": form}
        return render(request, 'main/post_add.html', context)
    
    if request.method == "POST":
        post_form = PostForm(request.POST, request.FILES)

        if post_form.is_valid():
            post = Post()
            post.author = request.user
            post.title = post_form.cleaned_data['title']
            post.text = post_form.cleaned_data['text']
            post.image = post_form.cleaned_data['image']
            post.publish()
            
            return post_list(request)
        

# 23/01/24
def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    title = 'Info about post'
    context = {'post': post, 'title': title}
    return render(request, template_name="main/post_detail.html", context=context)

# 01.02.24
def post_update(request, pk):
    # получаем объект модели Пост
    post = Post.objects.get(pk=pk)
    title = 'Изменить пост'

    # при отправке формы методом ПОСТ
    if request.method == "POST":
        # заполняем объект формы из запроса
        form = PostForm(request.POST, request.FILES, instance=post)
        # сохраняем форму
        if form.is_valid():
            form.save()
            return redirect("main:post_detail", pk=pk)
        
        # если метод ГЕТ    
    form = PostForm(instance=post)
    return render(request, "main/post_update.html", context={"form":form, "title":title, "menu":menu})


def post_delete(request, pk):   
    post = Post.objects.filter(pk=pk).first()

    if request.method == "POST":
        if "delete" in request.POST:
            post.delete()
            return redirect("main:post_list")
        if "cancel" in request.POST:
            return redirect("main:post_list")

    
    form = PostForm(instance=post)
    return render(request, "main/post_delete.html", context={"form":form, "menu":menu, "post":post})


# 06/02/24
def search(request):
    query = request.GET.get('q')
    ft = Q(title__icontains=query)| Q(text__icontains=query)
    # results = Post.objects.filter(author__username=query)
    results = Post.objects.filter(ft)
    return post_list(request, results)
# поиск по нескольким полям - магический оператор Q (meganit.com)

main/templates/main/about.html
{% extends "main/base.html" %}
{% block content %}
<h1>О сайте <h1/>
{% endblock content %}

main/templates/main/base.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html>
    <head>
        <title> {{title}} </title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>

    </head>

    <body>
      {% comment %} Зарегиться, войти, выйти {% endcomment %}
      {% if user.is_authenticated %}
      Привет, {{user.username}}
      <p><a href='{% url "users:logout" %}'>Выйти </a></p>
      {% endif %}

      {% if not user.is_authenticated %}
      <ul>
        <li><a href="{% url "users:register" %}"> Регистрация </a> </li>
        <li><a href="{% url "users:login" %}"> Войти </a></li>
      </ul>  
      {% endif %}

        {% block head %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url menu.0.url_name %}">{{menu.0.title}}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url menu.1.url_name %}"> {{menu.1.title}} </a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url menu.2.url_name %}"> {{menu.2.title}} </a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url menu.3.url_name %}"> {{menu.3.title}} </a>
                </li>
              </ul>
            </div>
          </nav>
        {% endblock head %}
        
        <img src='{% static 'img/img_blog.jpeg'%}'></img>
        
        <ul>
            {% for item in menu %}
            <h2><li> <a href='{% url item.url_name %}'> {{item.title}} </a> </li> </h2>
            {% endfor %}
        </ul>
        

        {% block content %}
        {% endblock %}
    </body>
</html>

{% comment %} {% url menu.0.url_name %} {% endcomment %}

main/templates/main/contacts.html
{% extends "main/base.html" %}
{% block content %}
<h1>Наши контакты <h1/>
{% endblock content %}

main/templates/main/index.html
{% extends "main/base.html" %}

{% block head %}
<h1>Мой блог <h1/>
{% endblock head %}

{% block content %}
<h3>Содержание сайта <h3/>
{% endblock content %}

main/templates/main/index_root.html
{% extends "main/base.html" %}

{% block content %}
<h1>Это главная страница сайта
</h1>
{% endblock content %}

main/templates/main/post_add.html
{% extends "main/base.html" %}

{% block head %}
    <h1>Создание нового поста <h1/>
{% endblock head %}

{% block content %}
<form action="{% url 'main:post_add' %}" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type = 'submit'> Создать пост </button>
</form>

{% endblock content %}

main/templates/main/post_delete.html
{% extends "main/base.html" %}

{% block content %}
<h1>Удалить пост?</h1>
<form method="POST" enctype="multipart/form-data">
    <p> Автор - {{post.author}} </p>
    <p> Заголовок - {{post.title}} </p>
    <p> Текст поста - {{post.text}} </p>
    <p> Дата создания - {{post.created_date}} </p>
    {% csrf_token %}
    <button type='submit' name='delete'>Удалить</button>
    <button type='submit' name='cancel'>Отменить</button>
</form>
{% endblock content %}

main/templates/main/post_detail.html
{% extends "main/base.html" %}
{% load thumbnail %}

{% block head %}
<h1> Information about post </h1>
{% endblock head %}

{% block content %}
    <p> Автор - {{post.author}} </p>
    <p> Заголовок - {{post.title}} </p>
    <p> Текст поста - {{post.text}} </p>
    <p> Дата создания - {{post.created_date}} </p>

    {% thumbnail post.image "300x300" as im %}
    <img src="{{im.url}}" width="{{im.width}}" height="{{im.height}}">
    {% endthumbnail%}
    <hr>
    {% if request.user == post.author %}
    <a href="{% url "main:post_update" pk=post.id%}">Редактировать</a>
    <a href="{% url "main:post_delete" pk=post.id%}">Удалить</a>
    {% endif %}
{% endblock content %}

main/templates/main/post_list.html
{% extends "main/base.html" %}

    {% block content %}
    <form method='get' action='{% url "main:search" %}'>
        <input type='text' name='q' value=''></input>
        <input type='submit' value='search'></input>
    </form>
        <table id='posts' border=1>
            <th>Author</th>
            <th>Title</th>
            <th>Text</th>
            <th>Created on</th>

        {% for post in posts %}
            <tr>
               <td align='center'> <a href="{% url "users:user_info" pk=post.author.id %}">{{post.author}}</a></td>
               <td align='center'> <a href="{% url 'main:post_detail' pk=post.id %}">{{post.title}}</a></td>
                <td align='center'> {{post.text}}</td>
                <td align='center'> {{post.created_date}}</td>
            </tr>
        {% endfor %}
    {% endblock content %}
        

    {% comment %} делаем кликабельным title {% endcomment %}

    {% comment %}
        06/02/24 фильтр кастомный
    {% endcomment %}

main/templates/main/post_update.html
{% extends "main/base.html" %}

{% block content %}
<h1>Редактирование поста</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit'>Изменить пост</button>
</form>
{% endblock content %}